######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 10 22:57:21 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += snowflakes.h
SOURCES += main.cpp snowflakes.cpp
RESOURCES += resources.qrc
